version: '3'

services:
  firefox:
    image: selenium/standalone-firefox:114.0-20230614
    expose:
      - 4444
    healthcheck:
      test: ["CMD-SHELL", "curl -s -I http://localhost:4444/ui | grep -q 'HTTP/1.1 200 OK'"]
      interval: 2s
      timeout: 5s
      retries: 120

  watch:
    build: .
    environment:
      FIREFOX_REMOTE: http://firefox:4444/wd/hub
    env_file:
      - ./.env
    depends_on:
      firefox:
        condition: service_healthy

